### ISSUE TITLE
Problem with "labelled" import - Stata 11

### ISSUE THREAD

**Issue by dcava** [hadley/haven#27] opened 2015-03-02 06:37 UTC
Hi,

Having an issue with importing labelled Stata variables. Appears to affect labelled numeric(long) stata type but not numeric(byte). Calling summary() fails with error below and as_factor gives a length error. 

``` {r}
>havtest$cav_n_stage
<Labelled>
 [1] 1 2 1 1 1 1 2 4 1 4 4 1 4 1 1 1 1 1 2 1 1 4 1 1 1 1 1 2 4 1 2
[32] 2 3 1 2 1 2 2 2 4 2 4 1 1 2 4 1 1 1 4 2 2 1 1 1 1 1 1 2 2 3 1
[63] 1 2 4 1
Labels:
N0 N1 N2 NX Nx 
 1  2  3  4  5 

>summary(havtest$cav_n_stage)
Error: `x` and `labels` must be same type

>as_factor(havtest$cav_n_stage)
Error in factor(match(x, attr(x, "labels")), labels = names(attr(x, "labels"))) : invalid 'labels'; length 5 should be 1 or 4
```

With that error, I thought it may be that there are no "Nx" (=5)  in this set. Indeed with a different numeric(long) var that has no redundant labels, I get the same error on using summary(), but as_factor() is successful. I can understand the as_factor() failing with redundant labels (although maybe it shouldn't...) but not sure why summary() fails?

By contrast, the numeric(byte) class seems fine:

```{r}
>havtest$abort_n2
<Labelled>
 [1] "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0"
[16] "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0"
[31] "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0"
[46] "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0"
[61] "0" "0" "0" "0" "0" "0"
Labels:
 no yes 
  0   1 

>summary(havtest$abort_n2)
   Length     Class      Mode 
       66  labelled character 

> as_factor(havtest$abort_n2)
 [1] no no no no no no no no no no no no no no no no no no no no no
[22] no no no no no no no no no no no no no no no no no no no no no
[43] no no no no no no no no no no no no no no no no no no no no no
[64] no no no
Levels: no yes
```

Not sure if this is just me not using things correctly!

Thanks,
David.

**Comment by hadley** [comment] 2015-03-04 19:33
This is a duplicate of #26

**Closed by hadley** 2015-03-04 19:33 UTC
