### ISSUE TITLE
Should levels = "values" preserve unlabelled values in as_factor()?

### ISSUE THREAD

**Issue by lionel-** [hadley/haven#134] opened 2015-11-11 16:51 UTC
```r
lab <- labelled(
  c("Z", "M", "M", "F", "X", "N/A"),
  labels = c(Male = "M", Female = "F", Refused = "X", "Not applicable" = "N/A"),
  is_na = c(FALSE, FALSE, TRUE, TRUE)
)

as_factor(lab)
#> [1] <NA>   Male   Male   Female <NA>   <NA>
#> Levels: Male Female

as_factor(lab, levels = "value")
#> [1] <NA> M    M    F    <NA> <NA>
#> Levels: M F
```
It would seem natural for "Z" to be preserved in the second example.

**Comment by hadley** [comment] 2015-11-11 16:57
Z?

**Comment by lionel-** [comment] 2015-11-11 16:59
the first value, not mentioned in `labels`.

**Comment by larmarange** [comment] 2015-11-11 17:03
Z should also be preserved in the first example.

In `labelled` package (https://github.com/larmarange/labelled), it appears that `as_factor` is working differentlu:

```r
> lab <- labelled(
+     c("Z", "M", "M", "F", "X", "N/A"),
+     labels = c(Male = "M", Female = "F", Refused = "X", "Not applicable" = "N/A"),
+     is_na = c(FALSE, FALSE, TRUE, TRUE)
+ )
> 
> lab
<Labelled character> 
[1] "Z"   "M"   "M"   "F"   "X"   "N/A"

Labels:
 value          label is_na
     M           Male FALSE
     F         Female FALSE
     X        Refused  TRUE
   N/A Not applicable  TRUE
> as_factor(lab)
[1] Z              Male           Male           Female         Refused        Not applicable
Levels: Female Male Not applicable Refused Z
> as_factor(lab, levels = "value")
[1] Z   M   M   F   X   N/A
Levels: F M N/A X Z
```

**Comment by lionel-** [comment] 2015-11-11 17:05
hmm I'm not sure it should be conserved in the first example. Perhaps with a new `levels = "both"`?

**Comment by larmarange** [comment] 2015-11-11 17:11
In `labelled` package,  this can be obtained with the parameter and/or the function `nolabel_to_na`. The choice has been to never convert to NA by default except if required explicitly.

Some of it was discussed already in https://github.com/hadley/haven/issues/81 but not solved, in particular regarding what should be the default behavior of `as_factor`.

**Comment by hadley** [comment] 2016-05-31 02:32
I think this is a duplicate of #81

**Closed by hadley** 2016-05-31 02:32 UTC
Labels: semantics
