### ISSUE TITLE
write_dta creates   numeric  columns that are "invisible" in Stata14>browse

### ISSUE THREAD

**Issue by lucasmation** [hadley/haven#161] opened 2016-05-20 00:32 UTC
To reproduce this weird issue do this: 
```
#In R
library(haven)
packageVersion("haven")
[1] ‘0.2.0’
write_dta(iris,
          'iris_data_Invisble_in_Stata_browse.dta')
```
```
*In Stata 14
use "iris_data_Invisble_in_Stata_browse.dta",clear
list // OK! data is shown normally to the output windown. The data is there
brwose // (this is Stata's equivlanet to View()). The data is invisible. The cells are all white, no content visible
```

I tested with Stat 12 > browse and you can see the data without this problem.

**Comment by hadley** [comment] 2016-05-30 16:08
@evanmiller is this a known problem? Do I just need to update to the latest readstat?

**Comment by evanmiller** [comment] 2016-05-30 16:11
I believe this is a duplicate of #138. Fixed a while back in ReadStat.

**Comment by hadley** [comment] 2016-05-30 16:58
Ok great :)

**Closed by hadley** 2016-05-30 16:58 UTC
