### ISSUE TITLE
Issues with the labelled class. Error: `x` and `labels` must be the same type

### ISSUE THREAD

**Issue by LaDilettante** [hadley/haven#155] opened 2016-04-13 23:54 UTC
Issue #59 is closed but is not actually fixed. Using the [same data posted in the original OP](http://doku.iab.de/fdz/liab/LIAB_LM_9310_v1_test_dta.zip), the following code still produces an error

```
d <- read_dta("LIAB_lm_9310_v1_pers.dta")
head(d)
```

> Error: `x` and `labels` must be same type

The following workaround solves the issue, but ideally it should not be necessary

`df[] <- lapply(df, unclass)`

**Comment by hadley** [comment] 2016-05-30 13:21
Duplicate of #86

**Closed by hadley** 2016-05-30 13:21 UTC
