### ISSUE TITLE
missing values treatment

### ISSUE THREAD

**Issue by dusadrian** [hadley/haven#74] opened 2015-06-02 20:55 UTC
The following public file might help explaining the issue:
http://www.columbia.edu/itc/hs/pubhealth/remler/8502/client_edit/datasets/gss.ZIP

```R
> library(haven)
> aa <- read_spss("gss.sav")
> table(aa$DEGREE)
  0   1   2   3   4 
279 780  90 234 113
> attr(aa$DEGREE, "labels")
  Less than HS    High school Junior college       Bachelor       Graduate 
             0              1              2              3              4 
Not applicable     Don't know      No answer 
             7              8              9 
> library(foreign)
> bb <- read.spss("gss.sav", use.value.labels=FALSE, to.data.frame=TRUE, use.missings=FALSE)
>  table(bb$DEGREE)
  0   1   2   3   4   8   9 
279 780  90 234 113   2   2
```

As you can see, haven has automatically recoded all the missing values to NAs, whereas read.spss() allows the user decide what to do with those values. It is important, for example in missing values imputation, to know which NAs are due to "Don't know" and which are due to "No answer".

Would it be possible to have haven's read_spss() function (and generally any function in haven that imports labelled variables) to allow users decide what to do with the missing values?

Adrian

**Comment by hadley** [comment] 2015-06-19 21:40
Hmmm, I need to think this through. ReadStat API now has:

> readstat_value_is_missing is now supplemented with two more functions to distinguish system-missing > (e.g. NaN values) from values that are considered missing on account of the missing value definitions:
>
> int readstat_value_is_system_missing(readstat_value_t value);
> int readstat_value_is_considered_missing(readstat_value_t value);

**Comment by hadley** [comment] 2015-06-19 21:42
Duplicate of #33.

**Closed by hadley** 2015-06-19 21:42 UTC
