### ISSUE TITLE
Error: Failed to parse when importing SAS dataset

### ISSUE THREAD

**Issue by nunsuch123** [hadley/haven#101] opened 2015-09-10 14:31 UTC
I have a SAS dataset with about 300 records and about 30 columns. I receive the following error when using read_sas("filename")

"Error: Failed to parse filename: A row in the file was not the expected length."

I am using RStudio version 0.99.465 for Mac. 

This works quite brilliantly on two other sas datasets of similar shape and content. What might be the issue?

**Comment by hadley** [comment] 2015-09-10 23:04
Can you share the data? That's the easiest way for me to debug

**Comment by nunsuch123** [comment] 2015-09-11 03:39
I really wish I could share it but it's clinical trial data. It would take me quite a while to recreate it with dummy information and I guess I might remove the problem in question if I do. It has 99 columns, not the 30 I originally thought. I can provide the field specifications (e.g. Field name, type, label, etc) if this is useful. Thank you for your support. 

Lauren

**Comment by hadley** [comment] 2015-09-11 11:46
It's likely to be something subtle with the formatting of the columns. Unfortunately it's impossible to know without a reproducible example.  Could you try doing a binary search (e.g. removing half the columns each time) to see if you can narrow down where the problem lies?

**Comment by evanmiller** [comment] 2015-09-19 20:33
@nunsuch123 are you using the latest GitHub version? That error message sometimes appears with the CRAN release but might be fixed in GitHub. If you're using the GitHub version, then any sample file that illustrates the issue would be helpful.

**Comment by evanmiller** [comment] 2015-10-08 15:09
I believe this issue is a duplicate of https://github.com/WizardMac/ReadStat/issues/35, which has been fixed in ReadStat master.

You can update to the latest ReadStat code with the instructions here: https://github.com/hadley/haven#updating-readstat

A workaround is to save the file without compression.

**Comment by evanmiller** [comment] 2015-10-09 13:31
Should be fixed by PR #114

**Closed** 2015-10-09 15:29 UTC
