### ISSUE TITLE
How does write_sav write labels to SPSS files?

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#21] opened 2015-02-22 14:23 UTC
More a question than an issue, but which format is required for vectors or the data.frame, so variable and value labels are saved to the SPSS file using write_sav? Value labels in created SPSS-files were all "invalid" (I tried to save vectors with attached label-values as well as factors with labels (no attributes).

**Comment by hadley** [comment] 2015-02-22 15:28
Factors should be saved correctly or you can use the labelled class. Could you please give a reproducible example?

**Comment by sjPlot** [comment] 2015-02-23 16:12
Here are reproducible examples. I'll try to attach .sav-files as well...

```
library(haven)

# first test, fails (see below)
s1 <- labelled(c("M", "M", "F"), c(Male = "M", Female = "F"))
s2 <- labelled(c(1, 1, 2), c(Male = 1, Female = 2))
write_sav(data.frame(s1, s2), "test.sav")
# Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) :
# cannot coerce class ""labelled"" to a data.frame
```

```
# second test, file "test.sav"
# results: see "test.sav" and "write_spss_1.png"
s1 <- factor(c(1, 1, 2), c(Male = 1, Female = 2), c("Male", "Female"))
attr(s1, "labels") <- c("M", "F")
names(attr(s1, "labels")) <- c("Male", "Female")
str(s1)
str(labelled(c("M", "M", "F"), c(Male = "M", Female = "F")))
write_sav(data.frame(s1), "test.sav")
```
![write_spss_1](https://cloud.githubusercontent.com/assets/4901179/6331360/f0869258-bb7e-11e4-9db0-25d33a83071f.png)


```
# third test, file "test2.sav"
# results: see "test2.sav" and "write_spss_2.png"
s1 <- factor(c(1, 1, 2))
s2 <- c(1,2,3)
attr(s2, "labels") <- c("1", "2", "3")
names(attr(s2, "labels")) <- c("lo", "mid", "hi")
write_sav(data.frame(s1, s2), "test2.sav")
```
![write_spss_2](https://cloud.githubusercontent.com/assets/4901179/6331365/fa8904ac-bb7e-11e4-8097-56b0ec17070c.png)

**Comment by afleishman** [comment] 2015-02-23 20:17
I apologize if this should be its own issue, but when I reproduce any of these examples I am unable to change the 'Type' within SPSS. It appears you can't change anything in the 'Variable View.'

**Comment by hadley** [comment] 2015-02-24 12:20
@evanmiller any thoughts on this problem? The code I'm using to create the variable labels is:

```cpp
labelSet = readstat_add_label_set(writer_, READSTAT_TYPE_INT32, name.c_str());

CharacterVector levels = as<CharacterVector>(x.attr("levels"));
for (int i = 0; i < levels.size(); ++i)
  readstat_label_int32_value(labelSet, i + 1, std::string(levels[i]).c_str());
```

@sjPlot the labels attribute does not affect factors. I'll add an `as.data.frame.labelled` method so you can create examples more easily. (But beware using `data.frame()` for creating examples because it can change the class of the input)

**Comment by hadley** [comment] 2015-02-24 12:23
@sjPlot it would be useful if you could create one simple example in two ways: one using R + `read_sav()` and the other directly in spss. If there's a problem with the ReadStat writer, that will help us figure it out

**Comment by evanmiller** [comment] 2015-02-24 16:00
@hadley I don't see anything wrong with your code so it's possible the bug is in ReadStat.

I don't have a copy of SPSS handy so @sjPlot it would help to have SAV files that represented the "expected" and "actual" output files.

**Comment by hadley** [comment] 2015-02-27 14:56
I think this is now fixed.

**Closed by hadley** 2015-02-27 14:56 UTC

**Comment by evanmiller** [comment] 2015-02-27 15:22
@hadley did you get confirmation from @sjPlot that the updated code works? (Or did you test w/ SPSS?) For my own peace of mind I'd like to be 100% sure that this bug is fixed.

**Comment by hadley** [comment] 2015-02-27 15:48
@evanmiller I didn't, but his code included here wouldn't trigger haven's handling of labelled vectors. My round trip code works, and is effectively the same as the code for factors (which we know works), so I'm fairly confident that this is ok

**Comment by evanmiller** [comment] 2015-02-27 16:17
@hadley sounds good, thanks for the clarification.

**Comment by sjPlot** [comment] 2015-03-01 12:32
I'll check it this evening or tomorrow.
