### ISSUE TITLE
Coerce int to numeric for `labelled`

### ISSUE THREAD

**Issue by sjPlot** [hadley/haven#167] opened 2016-05-30 19:44 UTC
Does not work:
```
x1 <- labelled(sample(1:3, size = 50, replace = T), c(lo = 1, mid = 2, hi = 3))
> Fehler: `x` and `labels` must be same type
```

Works:
```
x1 <- labelled(as.numeric(sample(1:3, size = 50, replace = T)), c(lo = 1, mid = 2, hi = 3))
```

Not so obvious for some users, maybe.

**Comment by hadley** [comment] 2016-05-30 19:53
Duplicate of #86

**Closed by hadley** 2016-05-30 19:53 UTC
