### ISSUE TITLE
read_sas: A row in the file was not the expected length

### ISSUE THREAD

**Issue by bethatkinson** [hadley/haven#38] opened 2015-03-06 00:13 UTC
I'm not seeing any obvious problems with the data - there are missing values scattered throughout.  Is there something specific I should look at that might sort out what is going on?

<pre><code>
d0 <- read_sas('sasdata/s114640.sas7bdat')
Error: Failed to parse sasdata/s114640.sas7bdat: A row in the file was not the expected length.

d1 <- sas.get('sasdata','s114640') 
Read 112 records
Read 40067 records

sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=C              
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grDevices datasets  splines   graphics  utils     stats     methods  
[8] base     

other attached packages:
[1] haven_0.0.0.9000 chron_2.3-45     gam_1.09.1       survival_2.37-7 
[5] rlocal_2.0.2    

loaded via a namespace (and not attached):
[1] Rcpp_0.11.4
</pre></code>

**Comment by hadley** [comment] 2015-03-06 11:56
I think this is a problem that @evanmiller will need to take a look at. Could you please provide a suitably anonymised/minimal version on a public site?

**Comment by bethatkinson** [comment] 2015-03-06 19:43
I looked at the data again today (fresh pair of eyes) and the issue is because the SAS data was compressed.  If I uncompress the data, it reads in fine.

**Comment by evanmiller** [comment] 2015-03-06 19:47
In that case, this issue is a duplicate of https://github.com/hadley/haven/issues/31 and depends on https://github.com/WizardMac/ReadStat/issues/21

**Closed** 2015-03-06 22:22 UTC
