### ISSUE TITLE
write_sav produces incorrect sysmis values

### ISSUE THREAD

**Issue by JKPeck** [hadley/haven#150] opened 2016-02-05 02:24 UTC
Create a data frame containing NA or NaN values and save it to a file using haven::write_sav.

Read the file into SPSS Statistics, and you will see that the NA or NaN values are not recognized as the SPSS sysmis value.

Dumping a sample sav file, it is apparent that the value being written for sysmis is incorrect.  The attached file, written by write_sav, illustrates the problem.
[fromhaven.zip](https://github.com/hadley/haven/files/118558/fromhaven.zip)
I have not checked the reverse - reading a sav file that contains sysmis values, but that might also be suspect.

I found this using version 0.2.0 on Windows 10.

**Comment by rtaph** [comment] 2016-02-13 22:44
I encountered the same problem reading in a .sav file. Whereas my .sav files previously read-in SPSS-defined missing values such as "don't know" correctly, now they get read-in as NA. The `labels` attribute in the resulting data frame still manages to recognize the existence of a defined missing level, but the underlying vector encodes all of these as NA.

The foreign package seems to have the same problem.

Using R version 3.2.3 (2015-12-10) on OSX.

**Comment by hadley** [comment] 2016-05-30 13:28
Duplicate of #70

**Closed by hadley** 2016-05-30 13:28 UTC
