### ISSUE TITLE
Why is NA converted to "2147483621" in Stata using write_dta?

### ISSUE THREAD

**Issue by dalewsteele** [hadley/haven#151] opened 2016-02-21 19:31 UTC
When I save the dataframe below (containing a single NA) and save as a Stata data file using:

`write_dta(test, "test.dta")`

When 'test.dta'  <https://dl.dropboxusercontent.com/u/6728326/test.dta>

is opened in Stata, the missing value is represented by the number "2147483621" (largest integer in long storage type)

I'm using haven_0.2.0.9000

```
test <- structure(list(PatNum = c(1, 2, 3, 4, 5, 6), EmplType = structure(c(3L, 
5L, 5L, 5L, 3L, 3L), .Label = c("Nurse Practitioner", "Physician Assistant", 
"Resident", "Fellow", "Faculty"), class = "factor"), Certification = structure(c(3L, 
3L, 3L, 3L, 3L, 3L), .Label = c("Emergency Medicine", "Pediatrics", 
"Pediatrics Emergency Medicine", "Emergency Medicine and Pediatrics", 
"Other"), class = "factor"), InjuryMech = structure(c(11L, 8L, 
5L, 6L, 12L, NA), .Label = c("Occupant in motor vehicle collision (MVC)", 
"Pedestrian struck by moving vehicle", "Bike rider struck by automobile", 
"Bike collision or fall from bike while riding", "Other wheeled transport crash", 
"Fall to ground from standing/walking/running", "Walked or ran into stationary object", 
"Fall from an elevation", "Fall down stairs", "Sports", "Assault", 
"Object struck head - accidental", "Other mechanism"), class = "factor")), .Names = c("PatNum", 
"EmplType", "Certification", "InjuryMech"), row.names = c(NA, 
6L), class = "data.frame")
```

**Comment by hadley** [comment] 2016-05-30 13:28
Duplicate of #70

**Closed by hadley** 2016-05-30 13:28 UTC
