### ISSUE TITLE
as_factor not working with NA:s from SPSS in 0.2.0.9000

### ISSUE THREAD

**Issue by gabrakadabra** [hadley/haven#120] opened 2015-10-15 21:41 UTC
Hi. I just installed the devversion of Haven `haven_0.2.0.9000`
and suddenly the `as_factor` fails when importing from SPSS using `read_sav()`,
and the variable contains NA:s

A fast test shows that 
```r
vh = labelled(c(1, 1, 2, 3, 99, NA), c(Car = 1, Bike = 2, Bus = 3, Unknown = 99))
as_factor(vh)
#>[1] Car     Car     Bike    Bus     Unknown <NA>   
#>Levels: Car Bike Bus Unknown
```
works fine but when I reproduce the data in SPSS I get an error.
```r
df <- haven::read_sav('test_haven.sav')
as_factor(df$vh)

#>Error in !attr(x, "is_na") : invalid argument type
```

I did not get the error in 0.2.0 from CRAN, which does not support the Unknown = 99 above.

**Comment by gergness** [comment] 2015-10-19 22:23
I had a similar issues in #93 and I believe the problem was an outdated version of Rcpp.

Can you run `devtools::session_info()` and post the results?

**Comment by gabrakadabra** [comment] 2015-10-21 13:22
My fix was to add `drop_na = F` to `haven::as_factor(xxx, drop_na= F)`
but this was not necessary in the previos version.

Here is my `session_info()`
```
 package    * version    date       source                          
 assertthat   0.1        2013-12-06 CRAN (R 3.2.1)                  
 colorspace   1.2-6      2015-03-11 CRAN (R 3.2.1)                  
 DBI          0.3.1      2014-09-24 CRAN (R 3.2.1)                  
 devtools     1.9.1      2015-09-11 CRAN (R 3.2.2)                  
 digest       0.6.8      2014-12-31 CRAN (R 3.2.1)                  
 dplyr      * 0.4.3      2015-09-01 CRAN (R 3.2.2)                  
 ggplot2    * 1.0.1      2015-03-17 CRAN (R 3.2.1)                  
 gridExtra  * 2.0.0      2015-07-14 CRAN (R 3.2.1)                  
 gtable       0.2        2015-09-11 Github (baptiste/gtable@4f8b139)
 GynopTools * 1.0        2015-10-15 local                           
 haven      * 0.2.0.9000 2015-10-15 Github (hadley/haven@cf00169)   
 knitr      * 1.11       2015-08-14 CRAN (R 3.2.2)                  
 lubridate  * 1.3.3      2013-12-31 CRAN (R 3.2.1)                  
 magrittr     1.5        2014-11-22 CRAN (R 3.2.1)                  
 MASS         7.3-43     2015-07-16 CRAN (R 3.2.2)                  
 memoise      0.2.1      2014-04-22 CRAN (R 3.2.1)                  
 munsell      0.4.2      2013-07-11 CRAN (R 3.2.1)                  
 plyr         1.8.3      2015-06-12 CRAN (R 3.2.1)                  
 proto        0.3-10     2012-12-22 CRAN (R 3.2.1)                  
 R6           2.1.1      2015-08-19 CRAN (R 3.2.2)                  
 Rcpp         0.12.1     2015-09-10 CRAN (R 3.2.2)                  
 reshape2     1.4.1      2014-12-06 CRAN (R 3.2.1)                  
 scales       0.3.0      2015-08-25 CRAN (R 3.2.2)                  
 stringi      0.5-5      2015-06-29 CRAN (R 3.2.1)                  
 stringr      1.0.0      2015-04-30 CRAN (R 3.2.1)                  
 tidyr      * 0.3.1      2015-09-10 CRAN (R 3.2.2)
```

**Comment by gergness** [comment] 2015-10-23 00:39
Strange, doesn't look like it is related to the version of Rcpp or devtools as those are what i have now. Glad you found a solution that works for you -- when I reinstalled haven the problem was fixed for me, and I'm not sure what was different the second time.

**Comment by sfirke** [comment] 2016-04-19 14:59
I am having this problem too.  In haven 0.2.0, I had a problem where for one particular variable, as_factor mapped the wrong levels and thus my frequency table was (insidiously) wrong.

In debugging that, I upgraded to haven 0.2.0.9000 and now `as_factor` calls yield the error described above.  I'm using the `drop_na = FALSE` workaround, which works (and the mis-mapping from 0.2.0 has vanished).  Here's my `session_info`:

```
Session info -------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, mingw32             
 ui       RStudio (0.99.878)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-04-19                  

Packages -----------------------------------------------------------------------------------------------
 package    * version    date       source                       
 assertthat   0.1        2013-12-06 CRAN (R 3.2.1)               
 corrplot   * 0.73       2013-10-15 CRAN (R 3.2.2)               
 curl         0.9.4      2015-11-20 CRAN (R 3.2.3)               
 DBI          0.3.1      2014-09-24 CRAN (R 3.2.1)               
 devtools   * 1.11.0     2016-04-12 CRAN (R 3.2.5)               
 digest       0.6.9      2016-01-08 CRAN (R 3.2.3)               
 dplyr      * 0.4.3      2015-09-01 CRAN (R 3.2.5)               
 git2r        0.13.1     2015-12-10 CRAN (R 3.2.3)               
 haven      * 0.2.0.9000 2016-04-19 Github (hadley/haven@11fb5f5)
 httr         1.0.0      2015-06-25 CRAN (R 3.2.1)               
 knitr        1.11       2015-08-14 CRAN (R 3.2.2)               
 magrittr   * 1.5        2014-11-22 CRAN (R 3.2.1)               
 memoise      1.0.0      2016-01-29 CRAN (R 3.2.4)               
 pacman     * 0.4.1      2016-03-30 CRAN (R 3.2.5)               
 R6           2.1.2      2016-01-26 CRAN (R 3.2.4)               
 Rcpp         0.12.4     2016-03-26 CRAN (R 3.2.4)               
 readxl     * 0.1.0      2015-04-14 CRAN (R 3.2.2)               
 stringi      1.0-1      2015-10-22 CRAN (R 3.2.2)               
 stringr      1.0.0      2015-04-30 CRAN (R 3.2.1)               
 tidyr      * 0.4.1      2016-02-05 CRAN (R 3.2.5)               
 withr        1.0.1      2016-02-04 CRAN (R 3.2.5)  
```

**Comment by hadley** [comment] 2016-05-30 16:57
Duplicate of #91.

**Closed by hadley** 2016-05-30 16:57 UTC
