### ISSUE TITLE
read_dta: seems not to import labeled extended missing values perfectly

### ISSUE THREAD

**Issue by kwenzig** [hadley/haven#160] opened 2016-05-17 09:59 UTC
In Stata extended missing values (like .a to .z) can have a value label. I used this Stata commands to construct a file, you can find here: https://oc.diw.de/index.php/s/B7A0HYIHdeMSxRC
```
clear
set obs 1
gen extended = .a
label define extendedlabel .a "extmissing a" 
label values extended extendedlabel
save extended, replace
```

With loaded haven 0.2.0.9000 I can write:
```
extended <- read_dta("extended.dta")
```
And I get no error. But if I type in RStudio 0.99.893 (or click on the name in environment pane), I get an error and the data.frame is not displayed:
```
> View(extended)
Error: `x` and `labels` must be same type
```
This could be an issue of RStudio, too.

**Comment by hadley** [comment] 2016-05-30 13:20
Duplicate of #86

**Closed by hadley** 2016-05-30 13:20 UTC
