### ISSUE TITLE
Loading file with .sas7bcat specified (still) results in crash

### ISSUE THREAD

**Issue by gergness** [hadley/haven#116] opened 2015-10-09 20:03 UTC
Thanks for the great package! I see that @evanmiller did some updates for sas7bcat files, and thought I'd send one of mine which I've never gotten to work (even before this most recent update). I can't share the full dataset, but even this minimal one with 2 observations and 3 variables causes a crash.

```
# First works okay, but the second causes a crash
data <- read_sas("https://dl.dropboxusercontent.com/u/2019891/haven_bug/subset.sas7bdat")

data2 <- read_sas("https://dl.dropboxusercontent.com/u/2019891/haven_bug/subset.sas7bdat", 
                  "https://dl.dropboxusercontent.com/u/2019891/haven_bug/formats.sas7bcat")

```

Here's my session info in case that is part of the problem again. Please let me know if there's anything else I can do to help.

```
Session info ---------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.484)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             
 date     2015-10-09                  

Packages -------------------------------------------------------------------------------------------------
 package    * version    date       source                       
 devtools     1.9.1      2015-09-11 CRAN (R 3.2.2)               
 digest       0.6.8      2014-12-31 CRAN (R 3.2.0)               
 haven      * 0.2.0.9000 2015-10-09 Github (hadley/haven@2923140)
 memoise      0.2.1      2014-04-22 CRAN (R 3.2.0)               
 Rcpp         0.12.1     2015-09-10 CRAN (R 3.2.2)               
 rstudioapi   0.3.1      2015-04-07 CRAN (R 3.2.0)
```

**Comment by evanmiller** [comment] 2015-10-09 20:05
What is the crash message?

**Comment by gergness** [comment] 2015-10-09 20:13
"R encountered a fatal error. The session was terminated."

I'm unaware of how to get more information when R crashes this way, as far as I know nothing is retained.

**Comment by gergness** [comment] 2015-10-09 20:13
(Would be happy to be proven wrong if someone here knows more)

**Comment by evanmiller** [comment] 2015-10-09 20:17
Thanks -- I am able to reproduce the crash on my machine, so I'll take it from here.

**Comment by gergness** [comment] 2015-10-09 20:20
Great, thanks!

**Comment by evanmiller** [comment] 2015-10-09 20:34
Just some notes for myself:

Version string: 8.0202M0WIN_ASRV 


The crash is occurring on the second block of the first "real" catalog page (i=3). The first block gives its size as 2040 (=(1+7)*255) but the second block appears to begin at 2015. Should add checks to prevent a crash, but the core issue is why there's a 25-byte discrepancy between the purported and actual block size.

**Comment by evanmiller** [comment] 2015-10-09 21:13
I think I am going to need more example files in order to debug this. This file has short pages (512 smaller than usual) and short blocks (25 bytes less than expected) -- if I can find other catalog files with similar properties (possibly, that crash in the same way), I'll try to find a pattern.

**Comment by evanmiller** [comment] 2015-10-09 21:55
Just so you know where I am -- I think I've crashed down the crash and have a fix ready. However, the file you provided seems to have surfaced a few other bugs in the software library. In particular it's choking on strings such as:

MT: ADULT (>= 20)  
HI: OAHU,OTH RACE 

Are these value labels, or another kind of data stored in the catalog file?

**Comment by evanmiller** [comment] 2015-10-09 22:53
Ok, I've pushed some patches which ought to fix this issue. Copy this into the dev version of haven: 

[readstat_sas.c](https://raw.githubusercontent.com/WizardMac/ReadStat/f286a8a38bd2209a3ea44295f79888499c742fdf/src/readstat_sas.c)

(Or see the instruction in the README for using the latest ReadStat code.)

Please close the issue if the fix works for you. Thanks!

**Comment by gergness** [comment] 2015-10-12 14:17
Thanks! The crash was fixed, but a lot of the labels are scrambled. I totally understand if you want to wait to see if other format libraries are structured this way, but here's what I've figured out about the problem.

The two variables I've included in the subset have the same formatting, which I believe SAS calls "SMOKE5F". They should be labelled as:
```
.B	=	DK/BLANK
.S	=	SKIP
1	=	41 CIGARETTES OR MORE
2	=	21 TO 40 CIGARETTES
3	=	11 TO 20 CIGARETTES
4	=	6    10 CIGARETTES
5	=	1 TO  5 CIGARETTES
6	=	LESS THAN 1 CIGARETTE
7	=	NONE (0 CIGARETTES)
```

But haven's label shows 
```
Labels:
          value                 label is_na
 -3.639647e-310 41 CIGARETTES OR MORE FALSE
 -4.563140e-310   21 TO 40 CIGARETTES FALSE
   1.000000e+00   11 TO 20 CIGARETTES FALSE
   2.000000e+00    6    10 CIGARETTES FALSE
   3.000000e+00    1 TO  5 CIGARETTES FALSE
   4.000000e+00 LESS THAN 1 CIGARETTE FALSE
   5.000000e+00   NONE (0 CIGARETTES) FALSE
   6.000000e+00              DK/BLANK FALSE
   7.000000e+00                  SKIP FALSE
```

In the full dataset,I think the pattern that determines whether the labels are scrambled is if it has  "multiple missings" such as `.B` and `.S` above. For example $STATEF, STRAT1IA, QX_TYPE, and LANGUAGE all have the correct labels.

**Comment by gergness** [comment] 2015-10-12 14:19
For the strings you mentioned above, do any start with "IA"? (I'm in Iowa, and it looks like those are state specific notes)

**Comment by evanmiller** [comment] 2015-10-12 14:23
Thanks for the information about the scrambled labels -- it appears to be related to the issue brought up over here: https://github.com/WizardMac/ReadStat/issues/38#issuecomment-147209465

The fix I provided there won't work with multiple missings. I'll need to dig around the file you provided some more.

And yes -- some of the strings start with IA, and many string appear to start with state postal codes. How does SAS interpret these notes, any idea?

**Comment by gergness** [comment] 2015-10-12 14:41
Are these the IA ones?
```
535	=	IA: NON-HISPANIC BLACK
536	=	IA: NON-HISPANIC WHITE/OTHER/UNKNOWN
537	=	IA: HISPANIC
```

This is from the label `STRATCF`, which combines all participating state's stratums into a single variable. Haven does not have a label for the variable that was supposed to be encoded by this label. 

The only difference I can think of is that this one will be much longer than other variable labels.

**Comment by evanmiller** [comment] 2015-10-12 15:07
Interesting, thanks -- it's probably encoded as a long label somehow. I didn't know catalog files could contain variable labels. I've opened a separate issue against ReadStat about this: https://github.com/WizardMac/ReadStat/issues/39

Since the crash is fixed, please close this issue and let's continue the discussion about jumbled value labels here: https://github.com/WizardMac/ReadStat/issues/40

**Closed** 2015-10-12 15:13 UTC
