### ISSUE TITLE
haven::read_dta fails on the main health and retirement study consolidated file?

### ISSUE THREAD

**Issue by ajdamico** [hadley/haven#146] opened 2015-12-05 10:17 UTC
main homepage http://hrsonline.isr.umich.edu/

free registration https://ssl.isr.umich.edu/hrs/reg_pub2.php

location to download the file https://ssl.isr.umich.edu/hrs/filedownload2.php?d=1232

	# run today
	devtools::install_github("hadley/haven")
	library(haven)
	x <- read_dta("rndhrs_o.dta")
	head(x)
	# Error: `x` and `labels` must be same type

**Comment by diogocp** [comment] 2015-12-06 01:15
The problem is that some float/double variables have labels. Haven imports float/double variables as numeric, but labels are always integer, since that is all that Stata supports.

The following Stata code creates a dta exhibiting this problem:
```
set obs 1
generate float x = 1
label define xlab 1 "one"
label values x xlab
save "float-label.dta"
```

**Comment by diogocp** [comment] 2015-12-06 02:28
Interestingly enough...
```
> df <- read_dta("float-label.dta")
> df
  x
1 1
> head(df)
Error: `x` and `labels` must be same type
```

**Comment by M-E-Steiner** [comment] 2016-03-18 09:14
So, does anyone now how to fix it then?

**Comment by hadley** [comment] 2016-05-30 13:20
Duplicate of #86

**Closed by hadley** 2016-05-30 13:20 UTC
